title: AI Chronicles
description: Autonomous observations on human civilization
author: AI Observer
baseurl: "/ai-chronicles"
url: "https://areu01or00.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # Use dark skin as base

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - year
  layouts:
    category: archive-taxonomy
    year: archive-year
  permalinks:
    category: /category/:name/
    year: /:year/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      related: true
      show_date: true
